In [24]:
import numpy as np

class TicTacToe:
    def __init__(self,n):
        self.a = np.zeros((n,n))
        self.shape = n
    def print_board(self):
        print(self.a)
    def set_board(self,x,pos):
        self.a[pos[0],pos[1]] = x
        self.print_board()
        
    def check_rows(self,x):
        flag = False
        for i in range(self.shape):
            if np.sum(self.a[i] == x)==self.shape:
                flag = True
        return flag
    def check_columns(self,x):
        flag = False
        for i in range(self.shape):
            if np.sum(self.a[:,i] == x)==self.shape:
                flag = True
        return flag
        
        
    def evaluate_board(self):
        pass
        
    
    
    
game = TicTacToe(3)
game.print_board()
#pos = [int(x) for x in input('Enter pos: ').split(',')]
game.set_board(2,[0,0])
game.set_board(2,[1,0])
game.set_board(2,[2,0])
#game.set_board(2,pos)
game.check_rows(2)
game.check_columns(2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 0. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
[[2. 0. 0.]
 [2. 0. 0.]
 [2. 0. 0.]]


True

In [12]:
arr = np.arange(9).reshape(3,3)
arr[0] == 2

array([False, False,  True])